### ISSUE TITLE
Migrate projects using bos-workspace

### ISSUE THREAD

**Issue by elliotBraem** [NEARBuilders/bos-workspace#45]
Creating this story to keep track of all the projects + repositories that are using bos-workspace and must be updated/maintained. 

Ideally we can update these to a stable version with a uniform structure, as well as using the reusable workflow, so there is minimal maintenance going forward.

- [ ] Discover BOS (has own gateway, too): https://github.com/nearbuilders/discoverbos
- [ ] Build DAO (own gateway): https://github.com/NEARBuilders/gateway
- [ ] Potlock: https://github.com/PotLock/bos-app
- [ ] Proof of Vibes: https://github.com/proofofvibes/vibes-components
- [ ] Blunt DAO: https://github.com/BluntDAO/bluntdao-bos-components
- [ ] Embeds: https://github.com/NEARBuilders/embeds
- [ ] Maps: https://github.com/NEARBuilders/maps
- [ ] Create: https://github.com/NEARBuilders/create
- [ ] Liberty DAO: https://github.com/NEARBuilders/libertydao
- [ ] Hackoween: https://github.com/nearbuilders/hackoween
- [ ] Questverse: https://github.com/Quest-Protocol/questverse-monorepo
